name: Deploy Web Server with Node.js

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js et http-server
        run: |
          npm install -g http-server

      - name: Lancer le serveur
        run: |
          cd build
          http-server -p 8000 &
          sleep 5
          curl -I http://localhost:8000
